package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func AddResponseSchema(resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Interact with Qwilt services.",
		Attributes: map[string]schema.Attribute{
			// CDN
			"env_type": schema.StringAttribute{
				Description:         "Qwilt CDN environment [prod,prestg,stage,dev]. May also be provided via QCDN_ENVTYPE environment variable.",
				MarkdownDescription: "FOR INTERNAL USE ONLY!! Qwilt CDN environment. [prod,prestg,stage,dev]",
				Optional:            true,
			},
			"username": schema.StringAttribute{
				Description:         "Username for Qwilt CDN Sites API. May also be provided via QCDN_USERNAME environment variable.",
				MarkdownDescription: "QC services username",
				Optional:            true,
			},
			"password": schema.StringAttribute{
				Description:         "Password for Qwilt CDN Sites API. May also be provided via QCDN_PASSWORD environment variable.",
				MarkdownDescription: "XApiToken from the Login API",
				Optional:            true,
				Sensitive:           true,
			},
			"xapi_token": schema.StringAttribute{
				Description:         "X-API Token for Qwilt CDN Sites API. May also be provided via QCDN_XAPI_TOKEN environment variable.",
				MarkdownDescription: "X-API Token generated by Qwilt CDN",
				Optional:            true,
				Sensitive:           true,
			},
		},
	}
}
